[mypy]
python_version = 3.12
pretty = True
show_error_codes = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
exclude = (?x)(^tests/|^\.venv/)

[mypy-app.services.*]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-app.models.*]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-app.utils.*]
disallow_untyped_defs = True
check_untyped_defs = True
